#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Oct 24, 2019 07:43:27 PM BDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
py3 = True
def set_Tk_var():
    global combobox
    combobox = tk.StringVar()
    global selectedButton
    selectedButton = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import forDBCollege
    forDBCollege.vp_start_gui()




